apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "purser.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "purser.name" . }}-controller
    helm.sh/chart: {{ include "purser.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "purser.name" . }}-controller
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "purser.name" . }}-controller
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "purser.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        command: 
        - "/controller"
        args:
        - "--cookieKey=purser-super-secret-key"
        - "--cookieName=purser-session-token"
        - "--log=info"
        {{- if .Values.controller.interactions }}
        - "--interactions=enable"
        {{- else }}
        - "--interactions=disable"
        {{- end }}
        - "--dgraphURL={{ include "purser.fullname" . }}-database"
        - "--dgraphPort=9080"
        ports:
          - name: http
            containerPort: 3030
            protocol: TCP
        resources:
          {{- toYaml .Values.controller.resources | nindent 12 }}
      initContainers:
      - name: init-sleep
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        command: ["/usr/bin/bash", "-c", "sleep 60"]
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
